help:			## Print Help Message
    @echo

frontend:	## Installing Frontend Component
	@sh components/frontend.sh

mongodb:	## Installing MongoDB Component
	@sh components/mongodb.sh

catalogue:	## Installing Catalogue Component
	@sh components/catalogue.sh

redis:			## Installing Redis Component
	@sh components/redis.sh

user:			## Installing User Component
	@sh components/user.sh

cart:			## Installing Cart Component
	@sh components/cart.sh

mysql:		## Installing MySql Component
	@sh components/mysql.sh

shipping:	## Installing Shipping Component
	@sh components/shipping.sh

payment:	## Installing Payment Component
	@sh components/payment.sh

rabbitmq:	## Installing RabbitMQ Component
	@sh components/rabbitmq.sh